# Generated by Django 4.2.7 on 2024-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
                ('growth_rate', models.CharField(max_length=100)),
                ('fall_color', models.CharField(max_length=100)),
                ('environmental_tolerances', models.CharField(max_length=200)),
                ('location_tolerances', models.CharField(max_length=200)),
                ('notes_suggested_cultivars', models.CharField(max_length=200)),
                ('tree_size', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
